#!/usr/bin/env python3
"""Codex hooks and small CLI companion for pi-instructions-ext's TASKS rules.

The hook path is intentionally fail-open: a missing/unreadable state file must
not stop a Codex turn. The CLI path is explicit and only writes files when the
user/model invokes a subcommand.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any


TASKS_PATH = Path("docs/TASKS.md")
RULES_PATH = Path("docs/RULES.md")
ARCHIVE_DIR = Path("docs/archives")
STATE_DIR = Path(tempfile.gettempdir()) / "codex-pi-instructions-ext"

TAG = "Auto-message: Please update docs/TASKS.md as needed."
TAG_STALE = (
    "Auto-message: docs/TASKS.md has changed on disk since the agent last touched it — "
    "re-read it before updating (a parallel session or the user may have edited it). "
    "Merge the changes instead of overwriting them."
)
RULES_STALE = (
    "Auto-message: docs/RULES.md has changed on disk since the agent last touched it — "
    "re-read it before continuing; the recording conventions may have changed."
)

VERIFY_MESSAGE = (
    "Auto-message: Walk through every item in docs/TASKS.md that needs user confirmation "
    '(sub-items marked "Confirm (user)", unfinished items whose completion condition is a '
    "user check such as behavior or visual verification, and explicitly unfinished work). "
    "Ask one concrete question per item in the user's language, with OK / problem / later "
    "options when an ask-user tool is available. Reflect each answer immediately: mark "
    'confirmed items "[x]" with a "— user-confirmed (date)" note, record problem reports as '
    '"— needs-fix: <summary>", and keep deferred items unchecked with "— pending confirmation". '
    "Never mark anything confirmed without an explicit user answer."
)

TASKS_TEMPLATE = """# TASKS

<!-- Work-instruction record. See docs/RULES.md for conventions. -->

## Active

## Completed
"""

RULES_TEMPLATE = """# TASKS recording rules

How this project records work instructions and their state (docs/TASKS.md).

## Recording

- Record each new instruction in docs/TASKS.md **before** starting on it,
  with a checklist of concrete steps as GFM checkboxes (`- [ ]` / `- [x]`).
- Keep the file up to date as work progresses. Skip pure acknowledgements
  ("yes", "continue") — judge what counts as an instruction.
- Respond and record in the user's language.

## User confirmation

- Items whose completion requires the user (behavior or visual checks,
  acceptance) get a sub-item prefixed "Confirm (user):" — never check it
  off yourself.
- When work finishes, ask the user about each pending confirmation item
  via the ask_user_question tool (one question per item, the concrete
  check described, options like OK / problem / later; plain text if the
  tool is unavailable). Never mark an item confirmed without an explicit
  user answer.
- Reflect answers as: "[x] … — user-confirmed (date)" · "— needs-fix:
  <summary>" · keep deferred items unchecked with "— pending
  confirmation".

## Parallel sessions

- Tag each top-level instruction you record with your session owner tag,
  e.g. "(s01a0)" (provided in the session-start message), and update only
  items carrying your own tag unless the user explicitly instructs
  otherwise.
- Re-read docs/TASKS.md before updating it — parallel sessions may have
  changed it. Merge, don't overwrite.

## Housekeeping

- If docs/TASKS.md accumulates many completed items, suggest that the user
  run /tasks-archive. The archive command is user-invoked — never move
  completed items yourself.
- When work finishes and the project has no git repository yet, suggest
  initializing one so the work and this record stay in history. At natural
  checkpoints, suggest committing uncommitted changes. The agent proposes —
  git is run only with the user's go-ahead.

<!-- Generated by pi-instructions-ext. Edit freely; the extension never
     overwrites this file once it exists. -->
"""


def rel(cwd: Path, path: Path) -> Path:
    return cwd / path


def file_hash(path: Path) -> str | None:
    try:
        return hashlib.sha1(path.read_bytes()).hexdigest()
    except (OSError, ValueError):
        return None


def snapshot(cwd: Path) -> dict[str, str | None]:
    return {
        "tasksHash": file_hash(rel(cwd, TASKS_PATH)),
        "rulesHash": file_hash(rel(cwd, RULES_PATH)),
    }


def session_key(cwd: Path, session_id: str) -> Path:
    key = hashlib.sha1(f"{cwd}\0{session_id}".encode()).hexdigest()
    return STATE_DIR / f"{key}.json"


def load_state(cwd: Path, session_id: str) -> dict[str, Any]:
    try:
        value = json.loads(session_key(cwd, session_id).read_text(encoding="utf-8"))
        return value if isinstance(value, dict) else {}
    except (OSError, ValueError, TypeError):
        return {}


def save_state(cwd: Path, session_id: str, state: dict[str, Any]) -> None:
    try:
        STATE_DIR.mkdir(parents=True, exist_ok=True)
        target = session_key(cwd, session_id)
        temp = target.with_suffix(".tmp")
        temp.write_text(json.dumps(state, sort_keys=True), encoding="utf-8")
        os.replace(temp, target)
    except OSError:
        pass


def owner_short(session_id: str) -> str:
    return hashlib.sha1(session_id.encode()).hexdigest()[:4] if session_id else "sess"


def project_root(cwd: Path) -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            cwd=cwd,
            check=False,
            capture_output=True,
            text=True,
        )
        root = result.stdout.strip()
        if result.returncode == 0 and root:
            return Path(root).resolve()
    except (OSError, ValueError):
        pass
    return cwd


def git_nudge(cwd: Path) -> str:
    tasks = rel(cwd, TASKS_PATH)
    if not tasks.exists() or not (cwd / ".git").exists():
        return ""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain", "--", str(TASKS_PATH)],
            cwd=cwd,
            check=False,
            capture_output=True,
            text=True,
        )
        if result.stdout.strip():
            return " docs/TASKS.md is not committed to git yet — suggest the user commit it so the record stays in history."
    except (OSError, ValueError):
        pass
    return ""


def session_pointer(cwd: Path, session_id: str) -> str:
    ready = rel(cwd, TASKS_PATH).exists() and rel(cwd, RULES_PATH).exists()
    if ready:
        return (
            'Auto-message: Start by reading docs/RULES.md — it defines how work instructions are '
            f'recorded in docs/TASKS.md. Your session owner tag is "(s{owner_short(session_id)})".'
            + git_nudge(cwd)
        )
    root = project_root(cwd) / ".codex" / "hooks" / "tasks_lifecycle.py"
    return (
        "Auto-message: docs/TASKS.md and docs/RULES.md are not set up yet — run "
        f'`python3 "{root}" --init` (it only creates what is missing), then read docs/RULES.md '
        f'and follow it when recording work instructions. Your session owner tag is "(s{owner_short(session_id)})".'
    )


def compact_pointer(cwd: Path) -> str:
    return (
        "Auto-message: The context was just compacted. The summary may not preserve item-level "
        "checklist state — re-read docs/TASKS.md to restore the current state before updating "
        "the record, and keep following docs/RULES.md."
        if rel(cwd, TASKS_PATH).exists()
        else ""
    )


def command_guidance(cwd: Path, prompt: str) -> str:
    command = prompt.strip()
    script = project_root(cwd) / ".codex" / "hooks" / "tasks_lifecycle.py"
    quoted = f'`python3 "{script}"'
    if command == "/tasks-init":
        return f"\n\nThe user requested TASKS initialization. Run {quoted} --init`, then read docs/RULES.md."
    if command == "/tasks-tidy":
        return f"\n\nThe user requested TASKS formatting. Run {quoted} --tidy` and report the result."
    if command == "/tasks-archive":
        return (
            f"\n\nThe user requested archiving completed TASKS items. Inspect the count first, ask for "
            f"confirmation if needed, then run {quoted} --archive --confirm`."
        )
    if command == "/tasks-clear":
        return f"\n\nThe user requested clearing TASKS. Confirm the destructive action, then run {quoted} --clear --confirm`."
    if command == "/tasks-verify":
        return f"\n\n{VERIFY_MESSAGE}"
    if command == "/tasks-blocked":
        return f"\n\nThe user requested unfinished TASKS items. Run {quoted} --list-blocked` and use the exact item reference in the next interaction."
    if command == "/tasks-completed":
        return f"\n\nThe user requested completed TASKS items for re-check. Run {quoted} --list-completed`."
    if command == "/tasks-info":
        return (
            "\n\nTASKS commands: /tasks-init initialize; /tasks-tidy normalize formatting; "
            "/tasks-archive move completed items; /tasks-clear reset with tombstone; "
            "/tasks-verify walk user confirmations; /tasks-blocked and /tasks-completed list item references."
        )
    return ""


def handle_hook(event: dict[str, Any]) -> None:
    cwd = Path(str(event.get("cwd") or os.getcwd())).resolve()
    session_id = str(event.get("session_id") or "unknown")
    name = str(event.get("hook_event_name") or "")
    state = load_state(cwd, session_id)

    if name == "SessionStart":
        source = str(event.get("source") or "startup")
        if source == "compact":
            text = compact_pointer(cwd)
            if text:
                print(text)
            return
        if not state.get("pointer_sent"):
            print(session_pointer(cwd, session_id))
            state["pointer_sent"] = True
        state["snapshot"] = snapshot(cwd)
        save_state(cwd, session_id, state)
        return

    if name == "UserPromptSubmit":
        current = snapshot(cwd)
        previous = state.get("snapshot")
        content = TAG
        if isinstance(previous, dict):
            tasks_stale = current["tasksHash"] is not None and current["tasksHash"] != previous.get("tasksHash")
            rules_stale = current["rulesHash"] is not None and current["rulesHash"] != previous.get("rulesHash")
            if rules_stale:
                content = RULES_STALE
            elif tasks_stale:
                content = TAG_STALE
        state["snapshot"] = current
        save_state(cwd, session_id, state)
        print(content + command_guidance(cwd, str(event.get("prompt") or "")))
        return

    if name == "Stop":
        state["snapshot"] = snapshot(cwd)
        save_state(cwd, session_id, state)


@dataclass
class Item:
    level: int
    checked: bool
    text: str
    children: list["Item"] = field(default_factory=list)
    trailing: list[str] = field(default_factory=list)


@dataclass
class Section:
    heading: str | None
    pre: list[str] = field(default_factory=list)
    roots: list[Item] = field(default_factory=list)


CHECKBOX_RE = re.compile(r"^([ \t]*)[-*+][ \t]*\[([ xX])\][ \t]*(.*)$")
CONFIRM_RE = re.compile(r"^confirm\s*\(\s*user\s*\)?\s*[:：\-—]*\s*", re.I)


def indent_width(raw: str) -> int:
    return sum(2 if char == "\t" else 1 for char in raw)


def parse_doc(text: str) -> list[Section]:
    sections = [Section(None)]
    current = sections[0]
    stack: list[Item] = []
    for raw in text.split("\n"):
        if re.match(r"^#{1,6} ", raw):
            current = Section(raw)
            sections.append(current)
            stack = []
            continue
        match = CHECKBOX_RE.match(raw)
        if match:
            level = indent_width(match.group(1)) // 2
            while stack and stack[-1].level >= level:
                stack.pop()
            node = Item(level, match.group(2).lower() == "x", match.group(3).rstrip())
            if stack:
                stack[-1].children.append(node)
            else:
                current.roots.append(node)
            stack.append(node)
            continue
        if stack:
            stack[-1].trailing.append(raw)
        elif current.roots:
            current.roots[-1].trailing.append(raw)
        else:
            current.pre.append(raw)
    return sections


def count_items(sections: list[Section]) -> int:
    def walk(item: Item) -> int:
        return 1 + sum(walk(child) for child in item.children)

    return sum(walk(root) for section in sections for root in section.roots)


def render_item(item: Item, depth: int, out: list[str]) -> None:
    text = item.text
    if depth > 0 and CONFIRM_RE.match(text):
        text = CONFIRM_RE.sub("Confirm (user): ", text)
    line = f"{'  ' * depth}- {'[x]' if item.checked else '[ ]'} {text}".rstrip()
    out.append(line)
    out.extend(item.trailing)
    for child in item.children:
        render_item(child, depth + 1, out)


def serialize(sections: list[Section]) -> str:
    out: list[str] = []
    for section in sections:
        if section.heading is not None:
            out.append(section.heading)
        out.extend(section.pre)
        for root in section.roots:
            render_item(root, 0, out)
    return "\n".join(out)


def ensure_files(cwd: Path) -> tuple[bool, bool]:
    tasks = rel(cwd, TASKS_PATH)
    rules = rel(cwd, RULES_PATH)
    tasks.parent.mkdir(parents=True, exist_ok=True)
    created_tasks = not tasks.exists()
    created_rules = not rules.exists()
    if created_tasks:
        tasks.write_text(TASKS_TEMPLATE, encoding="utf-8")
    if created_rules:
        rules.write_text(RULES_TEMPLATE, encoding="utf-8")
    return created_tasks, created_rules


def archive_items(cwd: Path, confirm: bool) -> int:
    file = rel(cwd, TASKS_PATH)
    if not file.exists():
        print("docs/TASKS.md does not exist.")
        return 0
    sections = parse_doc(file.read_text(encoding="utf-8"))
    moved: list[Item] = []
    remaining: list[Section] = []
    for section in sections:
        keep = [root for root in section.roots if not root.checked]
        moved.extend(root for root in section.roots if root.checked)
        if section.heading is None or keep or any(line.strip() for line in section.pre):
            remaining.append(Section(section.heading, section.pre, keep))
    if not moved:
        print("No completed items in docs/TASKS.md — nothing to archive.")
        return 0
    rendered: list[str] = []
    for item in moved:
        render_item(item, 0, rendered)
    day = datetime.now().strftime("%Y-%m-%d")
    stamp = datetime.now().strftime("%H:%M")
    archive = rel(cwd, ARCHIVE_DIR / f"TASKS-{day}.md")
    rendered_text = "\n".join(rendered).rstrip()
    block = f"## Archived {day} {stamp}\n\n{rendered_text}\n"
    print(f"{len(moved)} completed top-level item(s) would be moved to {archive}.")
    if not confirm:
        print("Re-run with --confirm to write the archive and update docs/TASKS.md.")
        return 0
    archive.parent.mkdir(parents=True, exist_ok=True)
    if archive.exists():
        previous = archive.read_text(encoding="utf-8")
        archive.write_text((previous if previous.endswith("\n") else previous + "\n") + "\n" + block, encoding="utf-8")
    else:
        archive.write_text(f"# TASKS archive\n\n{block}", encoding="utf-8")
    file.write_text(serialize(remaining), encoding="utf-8")
    print(f"Archived {len(moved)} item(s).")
    return 0


def list_items(cwd: Path, completed: bool) -> int:
    file = rel(cwd, TASKS_PATH)
    if not file.exists():
        print("docs/TASKS.md does not exist.")
        return 0
    sections = parse_doc(file.read_text(encoding="utf-8"))

    def walk(item: Item, chain: list[str]) -> None:
        current = chain + [item.text]
        is_needs_fix = bool(re.search(r"needs-fix", item.text, re.I))
        is_pending = bool(CONFIRM_RE.match(item.text)) and not item.checked
        if (completed and item.checked) or (not completed and (is_pending or is_needs_fix or (item.level == 0 and not item.checked))):
            print('"' + "\n".join(f"{'  ' * i}- {text}" for i, text in enumerate(current)) + '"')
        for child in item.children:
            walk(child, current)

    for section in sections:
        for root in section.roots:
            walk(root, [])
    return 0


def cli(cwd: Path, argv: list[str]) -> int:
    if not argv or argv[0] in {"-h", "--help"}:
        print("Usage: tasks_lifecycle.py --init | --tidy | --archive [--confirm] | --clear [--confirm] | --list-blocked | --list-completed")
        return 0
    command = argv[0]
    if command == "--init":
        created_tasks, created_rules = ensure_files(cwd)
        if not created_tasks and not created_rules:
            print("docs/TASKS.md and docs/RULES.md already exist — nothing to generate.")
        else:
            created = []
            if created_tasks:
                created.append("docs/TASKS.md")
            if created_rules:
                created.append("docs/RULES.md")
            print("Created " + ", ".join(created) + ". Read docs/RULES.md and follow it.")
        return 0
    file = rel(cwd, TASKS_PATH)
    if command == "--tidy":
        if not file.exists():
            print("docs/TASKS.md does not exist.")
            return 0
        original = file.read_text(encoding="utf-8")
        sections = parse_doc(original)
        if count_items(sections) == 0:
            print("No checklist items in docs/TASKS.md — nothing to tidy.")
            return 0
        tidied = serialize(sections)
        if tidied == original:
            print("docs/TASKS.md is already tidy.")
        else:
            file.write_text(tidied, encoding="utf-8")
            print("Tidied docs/TASKS.md. Item order preserved.")
        return 0
    if command == "--archive":
        return archive_items(cwd, "--confirm" in argv[1:])
    if command == "--clear":
        if not file.exists():
            print("docs/TASKS.md does not exist.")
            return 0
        if "--confirm" not in argv[1:]:
            print("Clearing docs/TASKS.md is destructive. Re-run with --confirm after user confirmation.")
            return 0
        tombstone = datetime.now().strftime("%Y-%m-%d %H:%M")
        suffix = " See git history if tracked." if (cwd / ".git").exists() else ""
        file.write_text(TASKS_TEMPLATE + f"\n<!-- Cleared by the user via /tasks-clear on {tombstone}.{suffix} -->\n", encoding="utf-8")
        print("docs/TASKS.md cleared and re-initialized.")
        return 0
    if command == "--list-blocked":
        return list_items(cwd, False)
    if command == "--list-completed":
        return list_items(cwd, True)
    print(f"Unknown command: {command}", file=sys.stderr)
    return 2


def main() -> int:
    if len(sys.argv) > 1:
        return cli(Path.cwd().resolve(), sys.argv[1:])
    try:
        raw = sys.stdin.read()
        event = json.loads(raw) if raw.strip() else {}
        if isinstance(event, dict):
            handle_hook(event)
        return 0
    except Exception:
        # A hook must not make the agent unusable because its optional state
        # bookkeeping failed. Deliberate CLI errors still use non-zero status.
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
